In [76]:
#결정나무의 깊이 = 갈림길 깊이
#결정나무의 랜덤 = 과적합 방지등의 이유로 무작위성 추가
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[1,2], [3,4], [1,2], [3,4]])
y = np.array([1,2,3,4])
kf = KFold(n_splits=2)


print(kf.get_n_splits(X))
print(kf)

2
KFold(n_splits=2, random_state=None, shuffle=False)


In [77]:
for train_idx, test_idx in kf.split(X):
    print("idx ")
    print(train_idx,test_idx)
    print("train data ")
    print(X[train_idx])
    print("test data ")
    print(X[test_idx])
    

idx 
[2 3] [0 1]
train data 
[[1 2]
 [3 4]]
test data 
[[1 2]
 [3 4]]
idx 
[0 1] [2 3]
train data 
[[1 2]
 [3 4]]
test data 
[[1 2]
 [3 4]]


In [78]:
import pandas as pd

red_wine = pd.read_csv("../cv_data/winequality-red.csv", sep=";")
white_wine = pd.read_csv("../cv_data/winequality-white.csv", sep=";")
red_wine["color"] = 1
white_wine["color"] = 0
wine = pd.concat([red_wine, white_wine])

In [79]:
wine["taste"] = [1. if grade>5 else 0. for grade in wine["quality"]]
X = wine.drop(["taste", "quality"], axis=1)
y = wine["taste"]


In [80]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test, = train_test_split(X, y, test_size=0.2,
                                                     random_state=13)

wine_tree = DecisionTreeClassifier(max_depth=2, random_state=13)
wine_tree.fit(X_train, y_train)


y_pred_tr = wine_tree.predict(X_train)
y_pred_test = wine_tree.predict(X_test)

print(accuracy_score(y_train, y_pred_tr))
print(accuracy_score(y_test, y_pred_test))



0.7294593034442948
0.7161538461538461


In [81]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)





In [82]:
for train_idx, test_idx in kfold.split(X):
    print(len(train_idx), len(test_idx))

5197 1300
5197 1300
5198 1299
5198 1299
5198 1299


In [83]:
cv_accuracy = []
for train_idx, test_idx in kfold.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    wine_tree_cv.fit(X_train, y_train)
    pred = wine_tree_cv.predict(X_test)
    cv_accuracy.append(accuracy_score(y_test, pred))
    
cv_accuracy

[0.6007692307692307,
 0.6884615384615385,
 0.7090069284064665,
 0.7628945342571208,
 0.7867590454195535]

In [84]:
import numpy as np
np.mean(cv_accuracy)

0.709578255462782

In [88]:
from sklearn.model_selection import StratifiedKFold

skfold = StratifiedKFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)

cv_accuracy = []

for train_idx, test_idx in skfold.split(X, y):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    wine_tree_cv.fit(X_train, y_train)
    pred = wine_tree_cv.predict(X_test)
    cv_accuracy.append(accuracy_score(y_test, pred))
    

    
cv_accuracy

[0.5523076923076923,
 0.6884615384615385,
 0.7143956889915319,
 0.7321016166281755,
 0.7567359507313318]

In [89]:
np.mean(cv_accuracy)

0.6888004974240539

In [90]:
#위작업을 간단하게 
from sklearn.model_selection import cross_val_score

skfold = StratifiedKFold(n_splits=5)
wine_tree_cv = DecisionTreeClassifier(max_depth=2, random_state=13)
cross_val_score(wine_tree_cv, X, y, scoring=None, cv=skfold)


array([0.55230769, 0.68846154, 0.71439569, 0.73210162, 0.75673595])